//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RALProject.Infrastructure.EntityFramework.RAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Business_UnitsTable
    {
        public int id { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public string jda_library { get; set; }
        public string jda_ip_address { get; set; }
    }
}
