//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RALProject.Infrastructure.EntityFramework.RAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RAL_DevEntities : DbContext
    {
        public RAL_DevEntities()
            : base("name=RAL_DevEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<UserServerDefult> UserServerDefults { get; set; }
        public DbSet<ReportTable> ReportTables { get; set; }
        public DbSet<Business_UnitsTable> Business_UnitsTable { get; set; }
        public DbSet<Last_LogIn> Last_LogIn { get; set; }
    }
}
