//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RALProject.Infrastructure.EntityFramework.RAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportTable
    {
        public int id { get; set; }
        public string report_id { get; set; }
        public Nullable<int> PONUMB { get; set; }
        public Nullable<int> POMRCV { get; set; }
        public string ASAUTO { get; set; }
        public Nullable<int> POLOC { get; set; }
        public string STRNAM { get; set; }
        public Nullable<int> POVNUM { get; set; }
        public string ASNAME { get; set; }
        public string POSDAT { get; set; }
        public string POCDAT { get; set; }
        public Nullable<int> IVPLTI { get; set; }
        public Nullable<int> IVPLHI { get; set; }
        public string LOCATION { get; set; }
        public Nullable<int> INUMBR { get; set; }
        public string IDESCR { get; set; }
        public string IUPC { get; set; }
        public string POMUM { get; set; }
        public Nullable<decimal> ORDERQTY { get; set; }
    }
}
